Update haproxy's init script with init metadata.

diff --git a/public/haproxy/haproxy b/public/haproxy/haproxy
--- a/public/haproxy/haproxy
+++ b/public/haproxy/haproxy
@@ -1,4 +1,13 @@
 #!/bin/sh
+### BEGIN INIT INFO
+# Provides:          haproxy
+# Required-Start:    $syslog
+# Required-Stop:     $syslog
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
+# Short-Description: Haproxy init.d script for Ubuntu or other *nix.
+# Description:       Haproxy init.d script for Ubuntu or other *nix.
+### END INIT INFO
 #
 # custom haproxy init.d script, by Mattias Geniar
 # Modified by Rico Sta. Cruz for Server Wizard
@@ -7,18 +16,9 @@
 # description: haproxy is a TCP loadbalancer
 # probe: true
 
-# Source function library.
-. /etc/rc.d/init.d/functions
-
-# Source networking configuration.
-. /etc/sysconfig/network
-
 HAPROXY_CONF=/etc/haproxy/haproxy.cfg
 HAPROXY_BIN=/usr/local/sbin/haproxy
-HAPROXY_PID=$HAPROXY_PID
-
-# Check that networking is up.
-[ ${NETWORKING} = "no" ] && exit 0
+HAPROXY_PID=/var/run/haproxy.pid
 
 [ -f $HAPROXY_BIN ] || exit 0
 [ -f $HAPROXY_CONF ] || exit 0
@@ -28,63 +28,50 @@ checkconfig() {
     # Check the config file for errors
     $HAPROXY_BIN -c -q -f $HAPROXY_CONF
     if [ $? -ne 0 ]; then
-            echo "Errors found in configuration file."
-            return 1
-      fi
+        echo "Errors found in configuration file."
+        return 1
+    fi
 
-    # We're OK!
     return 0
 }
 
 start() {
-    # Check config
     checkconfig || return 1
 
     echo -n "Starting HAProxy: "
-    daemon $HAPROXY_BIN -D -f $HAPROXY_CONF -p $HAPROXY_PID
+    $HAPROXY_BIN -D -f $HAPROXY_CONF -p $HAPROXY_PID
 
     RETVAL=$?
     echo
-      [ $RETVAL -eq 0 ] && touch /var/lock/subsys/haproxy
-      return $RETVAL
+
+    #[ $RETVAL -eq 0 ] && touch /var/lock/subsys/haproxy
+    return $RETVAL
 }
 
 stop() {
     echo -n "Shutting down HAProxy: "
-      killproc haproxy -USR1
+    kill -USR1 $(cat $HAPROXY_PID) || killall -USR1 haproxy
 
-      RETVAL=$?
-      echo
-      [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/haproxy
-      [ $RETVAL -eq 0 ] && rm -f $HAPROXY_PID
-      return $RETVAL
+    RETVAL=$?
+    echo
+
+    #[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/haproxy
+    [ $RETVAL -eq 0 ] && rm -f $HAPROXY_PID
+    return $RETVAL
 }
 
 restart() {
-    $HAPROXY_BIN -c -q -f $HAPROXY_CONF
-        if [ $? -ne 0 ]; then
-                echo "Errors found in configuration file."
-                return 1
-        fi
-
+    checkconfig || return 1
     stop
-      start
+    start
 }
 
 check() {
       $HAPROXY_BIN -c -q -V -f $HAPROXY_CONF
 }
 
-rhstatus() {
-      status haproxy
-}
-
 reload() {
-    $HAPROXY_BIN -c -q -f $HAPROXY_CONF
-        if [ $? -ne 0 ]; then
-                echo "Errors found in configuration file."
-                return 1
-        fi
+    checkconfig || return 1
 
     echo -n "Reloading HAProxy config: "
     $HAPROXY_BIN -f $HAPROXY_CONF -p $HAPROXY_PID -sf $(cat $HAPROXY_PID)
